### ISSUE TITLE
[Feature]: implement multiple languages support

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront-community/vendure#142]
### How the project can be improved?

For now, we do not have a support for multiple languages. Lets add them

### What are the acceptance criteria?

- [ ]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zmilan** [comment]
Hi @Baroshem,
I am interested in implementing this

**Comment by Baroshem** [comment]
Sure, please go on. If you have questions, please let me know :)

**Comment by Baroshem** [comment]
Hi @zmilan 

How are you? Do you need any help with that task? :)

**Comment by zmilan** [comment]
@Baroshem I am sorry, but I become too busy last days... I hope to get more time in next days, but if this is urgent, maybe it is better that someone else take it from me... I didn't get a chance to start it yet...

**Comment by Baroshem** [comment]
@zmilan 

No worries, I will unasign one of the tasks then as I would like to have this functionality as a part of of 1.1.0 release :)

**Comment by zmilan** [comment]
@Baroshem sure, thanks... I would become more active as soon as I free some time...

**Comment by julienTeam** [comment]
@Baroshem Hi, I moved forward to enable the localisation feature on the Vendure server side.
Inspired by the VSF Commercetools integration, a short new component in api-client/source/ext that extends the apiClient and dynamicaly change the url of the Vendure API endpoint according to the country code value provided by the cookie "i18n_redirected" (ie: api.uri = <host>/shop-api&languageSelect=<countrycode provided by i18n>
It's now working fine :-)

I also fixed a bug in the language switch selector that didn't seem to work correctly by changing the value of the 'strategy' key defined in i18n options in the nuxt.config.js file to  **strategy: 'prefix'** instead of **strategy: 'no_prefix'** , it seems to correct the issue. However, I still have a problem because when I switch language on the language selector module, all the text are correctly translated in the selected languages but i need to manualy reload the URL on the browser to force all modules to reload with the correct data (ie product or categories ...) . Would you have an idea on how to force the reload of all the components that are displayed on the page after having selected a language in LocaleSelector.vue ?

Thank you !

**Comment by Baroshem** [comment]
Awesome @julienTeam !

Could you create a PR with your changes? I will take a look at it as I think I have solved similar issue before 😉

**Comment by Baroshem** [comment]
Done in #160
