### ISSUE TITLE
How could i modify Country list at checkout page?

### ISSUE THREAD

**Issue by blackyzero** [vuestorefront-community/vendure#226]
### What is your question / Please describe your issue

Hello,

How could i modify the list country at checkout page? It it been fetched from Vendure API?
For now, it shows Italy and Poland in Shipping and Billing.

Thank you.

### What version of vendure are you using?

1.6.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment]
Hey, it can be modified both on the VSF and Vendure side

https://github.com/vuestorefront-community/vendure/blob/develop/packages/theme/helpers/constants.ts

In this file, you can decide what countries you want to be accessible from the checkout page.

Keep in mind that I linked the page in vue storefront repo. You will probably have a bit dofferent path due to VSF & Vendure template 🙂

**Comment by blackyzero** [comment]
Got it. thanks @Baroshem :)

**Comment by Baroshem** [comment]
Great, closing the issue then :)
